name: Translation Sync

on:
  schedule:
    - cron: '0 2 * * 1'
  workflow_dispatch:

jobs:
  sync:
    permissions:
      contents: write
      pull-requests: write
    uses: owncloud/reusable-workflows/.github/workflows/translation-sync.yml@add-translation-sync
    with:
      mode: old
    secrets:
      TX_TOKEN: ${{ secrets.TX_TOKEN }}
